import { EVENTS } from "../model";

export interface IMediaContent {
    videoElement: HTMLVideoElement;
    manifestUrl: URL;
}

export const videoElementEvents = [
    EVENTS.VIDEO_PLAY,
    EVENTS.VIDEO_PAUSE,
    EVENTS.VIDEO_PLAYING,
    EVENTS.VIDEO_ENDED,
    EVENTS.VIDEO_WAITING,
    EVENTS.VIDEO_CANPLAY,
    EVENTS.VIDEO_CANPLAYTHROUGH,
    EVENTS.VIDEO_LOADEDMETADATA,
    EVENTS.VIDEO_LOADEDDATA,
    EVENTS.VIDEO_PROGRESS,
    EVENTS.VIDEO_SEEKING,
    EVENTS.VIDEO_SEEKED,
    EVENTS.VIDEO_TIMEUPDATE,
    EVENTS.VIDEO_VOLUMECHANGE,
    EVENTS.VIDEO_ERROR
];